test e2e tests with the new auth, kind cluster : fix image

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -63,9 +63,12 @@ jobs:
 
       - name: Create k8s Kind Cluster
         uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde
+
       - name: Check Kind Cluster
         run: |
-          kubectl get nodes
+          kubectl run --image=nginx test-nginx --restart=Never --command -- sleep 3600
+          kind load docker-image ghcr.io/deliveryhero/gcp-config-connector-tagging-operator:1.1.2 --name kind || echo "Failed to load image. Check if the image exists and is accessible."
+          kubectl get pods
 
       - name: Run E2E Tests
         run: |
